repos:
 - repo: https://github.com/awslabs/git-secrets.git
   rev: 0652a46d8a02b913104363f8d9f91d7f8f040f7c
   hooks: 
   - id: git-secrets
 - repo: https://github.com/psf/black
   rev: 27932494bcefac03497dd92dcf0c59a04c10d757
   hooks:
   - id: black
 - repo: https://github.com/PyCQA/flake8.git
   rev: 16c371d41cd742f975171826de0ad5d707162c1d
   hooks:
   - id:  flake8
     args: 
     -  "--max-line-length=120"
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v4.3.0
    hooks:
    - id: check-added-large-files